version: '3.1'

services:

  db:
    container_name: postgresql
    image: postgres
    # automatically restarts the container - Docker daemon on restart or
    # the container itself is manually restarted
    restart: always

    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: s344410
      POSTGRES_PASSWORD: 8D8q7Srz7k8YylYO
      POSTGRES_DB: studs
    ports:
      - "5432:5432"
